[build-system]
requires = ["maturin>=1.4"]
build-backend = "maturin"

[project]
name = "pyaisa"
version = "1.0.0"
description = "ISA Model computed in Rust using PyO3"
authors = [{ name = "Giorgio" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"

dependencies = ["numpy"]

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]

[tool.pytest.ini_options]
addopts = "--cov=pyaisa --cov-report=term-missing"

[tool.maturin]
module-name = "pyaisa._core"
compatibility = "manylinux_2_28"
