from __future__ import annotations

import numpy as np
from numpy.typing import NDArray

from pyaisa.pyaisa_core import (
    altitude_to_fl,
    cas_to_eas,
    cas_to_mach,
    cas_to_tas,
    density_altitude,
    dew_point,
    dynamic_pressure,
    dynamic_viscosity_sutherland,
    eas_to_cas,
    eas_to_tas,
    equivalent_potential_temperature,
    fl_to_altitude,
    freezing_fraction,
    geometric_to_fl,
    geometric_to_geopotential,
    geopotential_to_geometric,
    gust,
    icing_severity,
    indicated_altitude,
    kinematic_viscosity,
    lwc,
    mach,
    mach_from_tas,
    mach_moist,
    mach_to_cas,
    mixing_ratio,
    moist_air_density,
    moist_lapse_rate,
    moist_speed_of_sound,
    moist_static_energy,
    potential_temperature,
    prandtl_glauert,
    pressure_altitude,
    reynolds_number,
    saturation_vapor_pressure,
    speed_of_sound,
    stagnation_entropy,
    stagnation_pressure,
    stagnation_temperature,
    supercooled_fraction,
    tas_to_cas,
    tas_to_eas,
    tas_to_mach_moist,
    vapor_pressure,
    virtual_potential_temperature,
    virtual_temperature,
    wet_bulb_temperature,
    wind_ekman,
    wind_linear_shear,
    wind_loglaw,
    wind_loglaw_displaced,
    wind_power_law,
)
